### ISSUE TITLE
ModuleNotFoundError: No module named 'sigma.pipelines.sentinelasim.microsoft365defender

### ISSUE THREAD

**Issue by aaronblancoCCRD** [AttackIQ/pySigma-backend-kusto#25]
Hi, so I am trying to use the kust query backend. I have uninstalled and reinstalled sigma_cli and the pysigma-backend-kusto via pip and through the cli's plugin install module. After installing the plugin and attempting to do a rule conversion I get this error 

 `Traceback (most recent call last):
  File "/home/ablanco/.cache/pypoetry/virtualenvs/sigma-cli-7cxQ9pcA-py3.10/bin/sigma", line 3, in <module>
    from sigma.cli.main import main
  File "/home/ablanco/Projects/sigma-cli/sigma/cli/main.py", line 32, in <module>
    from .list import list_group
  File "/home/ablanco/Projects/sigma-cli/sigma/cli/list.py", line 13, in <module>
    plugins = InstalledSigmaPlugins.autodiscover()
  File "/home/ablanco/.cache/pypoetry/virtualenvs/sigma-cli-7cxQ9pcA-py3.10/lib/python3.10/site-packages/sigma/plugins.py", line 194, in autodiscover
    pipelines = cls._discover_module_directories(
  File "/home/ablanco/.cache/pypoetry/virtualenvs/sigma-cli-7cxQ9pcA-py3.10/lib/python3.10/site-packages/sigma/plugins.py", line 89, in _discover_module_directories
    imported_module = importlib.import_module(mod.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ablanco/.cache/pypoetry/virtualenvs/sigma-cli-7cxQ9pcA-py3.10/lib/python3.10/site-packages/sigma/pipelines/sentinelasim/__init__.py", line 1, in <module>
    from .sentinelasim import sentinel_asim_pipeline
  File "/home/ablanco/.cache/pypoetry/virtualenvs/sigma-cli-7cxQ9pcA-py3.10/lib/python3.10/site-packages/sigma/pipelines/sentinelasim/sentinelasim.py", line 22, in <module>
    from .microsoft365defender import (
ModuleNotFoundError: No module named 'sigma.pipelines.sentinelasim.microsoft365defender'`

Any reason this should be happening with the updated plugin?

**Comment by slincoln-aiq** [comment]
Hello,

Thanks for reporting this. I just released v0.3.3, which should fix this issue.  Let me know if you still have any issues after updating
